In [2]:
import numpy as np

In [42]:
def createData(number_of_subsets, columns, universe_size, rangen):
  cost_values = np.random.randint(10, size=1)
  subsets = np.random.randint(rangen, size=(number_of_subsets, columns))
  album = np.random.choice(range(rangen), 20, replace=False)
  print(f'Album Universe [{universe_size}] {album} \n')
  print(f'Columns [{columns}] \nSubsets [{number_of_subsets}] \n {subsets}: \n')
  print(f'Cost value for each subset \n {cost_values} \n')
  print(f'Range of random generator {rangen} \n')


In [48]:
## 1 step, Create columns
## 2 create cost value
## 3 iterate through list of columns and select random index
## 4 save random index number in a dictionary to make sure theres no duplicates
## 6 adjust the size of the dictionary to fit the specified album length
def create_album(size, subset):
  subset_values = subset.flatten()
  subset_len = len(subset_values)
  album = dict()
  for i in range(size):
    randomIndex = np.random.randint(subset_len, size=1)[0]
    value = subset_values[randomIndex]
    if value not in album:
      album[value] = 1
    else:
      value = subset_values[randomIndex + 1]
      album[value] = 1
    
  return album

def create_subsets(number_of_subsets, columns, rangen):
  subsets = np.random.randint(rangen, size=(number_of_subsets, columns))
  return subsets

def create_cost_values(number_of_subsets):
  return np.random.rand(number_of_subsets)

def define_dataset(number_of_subsets, columns, album_size, rangen):
  subs = create_subsets(number_of_subsets, columns, rangen)
  cost_values = create_cost_values(number_of_subsets)
  album = create_album(album_size, subs)

  # TO DO : Create logic to save file to csv using pandas

  return subs, cost_values, album


subs, cost_values, album = define_dataset(20, 5, 20, 200)

print(subs)
print('\n')
print(cost_values)
print('\n')
print(album)

[[ 13  34  70 156   8]
 [ 94  24  55 120  14]
 [181  67  16  15  87]
 [195   0 137  66  55]
 [130 154  14  70   3]
 [170  93 119  80  28]
 [192  90  51  66  65]
 [ 82 145  56  14  88]
 [ 16  68  44  60  84]
 [106 116   4 109 126]
 [  7  94 125   2   3]
 [ 51 177 171 129 192]
 [ 32  28 132 137 119]
 [ 62 182  41 163  60]
 [199 194  64  39  48]
 [ 97 137  10  79   3]
 [  7  47 188  34 119]
 [  6  51 106  12 103]
 [ 41 180 116 166   3]
 [141  56 140 199 188]]


[0.6962617  0.82188358 0.32868721 0.48433683 0.55167637 0.74764219
 0.55729848 0.63955246 0.0296609  0.71714328 0.0903144  0.03018992
 0.84987335 0.02988182 0.93248805 0.10458819 0.22761299 0.67010586
 0.59274047 0.785812  ]


{84: 1, 0: 1, 171: 1, 62: 1, 141: 1, 47: 1, 137: 1, 97: 1, 132: 1, 70: 1, 56: 1, 48: 1, 60: 1, 192: 1, 106: 1, 156: 1, 116: 1, 67: 1}


In [49]:
## sort subsets by cost
## asign number of album occurences in each subset
## select which subsets have the best occurences per cost value
## sum all costs

def solve_greedy(subsets, costs, album):
  total = 0
  winning_list = list()
  occurences_per_cost = dict()
  subset_cost = list()

  # create tuple array (subset, cost)
  for i in range(len(subsets)):
    tup = subsets[i], costs[i]
    subset_cost.append(tup)

  sorted_subsets = sorted(subset_cost, key=lambda x: x[1])
  print(sorted_subsets)

solve_greedy(subs, cost_values, album)

[(array([16, 68, 44, 60, 84]), 0.029660895517682584), (array([ 62, 182,  41, 163,  60]), 0.029881820777131085), (array([ 51, 177, 171, 129, 192]), 0.030189924561907278), (array([  7,  94, 125,   2,   3]), 0.0903144019053661), (array([ 97, 137,  10,  79,   3]), 0.10458818722192675), (array([  7,  47, 188,  34, 119]), 0.22761298551977693), (array([181,  67,  16,  15,  87]), 0.32868720764103254), (array([195,   0, 137,  66,  55]), 0.4843368270026802), (array([130, 154,  14,  70,   3]), 0.551676366740287), (array([192,  90,  51,  66,  65]), 0.5572984766146448), (array([ 41, 180, 116, 166,   3]), 0.5927404674234472), (array([ 82, 145,  56,  14,  88]), 0.639552457891749), (array([  6,  51, 106,  12, 103]), 0.6701058637108916), (array([ 13,  34,  70, 156,   8]), 0.696261704317144), (array([106, 116,   4, 109, 126]), 0.7171432818971046), (array([170,  93, 119,  80,  28]), 0.7476421857084561), (array([141,  56, 140, 199, 188]), 0.7858119958834716), (array([ 94,  24,  55, 120,  14]), 0.821883575