<a href="https://colab.research.google.com/github/AaronARdz/set_covering/blob/main/randomDatasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [42]:
def createData(number_of_subsets, columns, universe_size, rangen):
  cost_values = np.random.randint(10, size=1)
  subsets = np.random.randint(rangen, size=(number_of_subsets, columns))
  album = np.random.choice(range(rangen), 20, replace=False)
  print(f'Album Universe [{universe_size}] {album} \n')
  print(f'Columns [{columns}] \nSubsets [{number_of_subsets}] \n {subsets}: \n')
  print(f'Cost value for each subset \n {cost_values} \n')
  print(f'Range of random generator {rangen} \n')


In [178]:
## 1 step, Create columns
## 2 create cost value
## 3 iterate through list of columns and select random index
## 4 save random index number in a dictionary to make sure theres no duplicates
## 6 adjust the size of the dictionary to fit the specified album length
def create_album(size, subset):
  subset_values = subset.flatten()
  subset_len = len(subset_values)
  album = dict()
  for i in range(size):
    randomIndex = np.random.randint(subset_len, size=1)[0]
    value = subset_values[randomIndex]
    if value not in album:
      album[value] = 0
    else:
      value = subset_values[randomIndex + 1]
      album[value] = 0
    
  return album

def create_subsets(number_of_subsets, columns, rangen):
  subsets = np.random.randint(rangen, size=(number_of_subsets, columns))
  return subsets

def create_cost_values(number_of_subsets):
  return np.random.rand(number_of_subsets)

def define_dataset(number_of_subsets, columns, album_size, rangen):
  subs = create_subsets(number_of_subsets, columns, rangen)
  cost_values = create_cost_values(number_of_subsets)
  album = create_album(album_size, subs)

  # TO DO : Create logic to save file to csv using pandas

  return subs, cost_values, album


subs, cost_values, album = define_dataset(50, 10, 50, 100)

print(subs)
print('\n')
print(cost_values)
print('\n')
print(album)

[[86 77 31  0 73 11 26 91 88 36]
 [58  0 76 79 49 49 73 29 47 24]
 [ 3 36 50 25  6 92 99 35 45 46]
 [25 40 53 39  4 61 61 28 15 30]
 [73 66 13  0 58 45 31 74 73 11]
 [27 58 97 43 25 94 18 28 70 66]
 [84 73  1 15 86 39 65 43 35 81]
 [27  2 83 90 72 51 88 20 96 30]
 [66 68 42 13 98 41 39 92 74 85]
 [48 87 23 40 57 57 21 45 53  6]
 [98 33 25 44 78 47 91 37 93 83]
 [93 91 38 90 40  2 87 18 16 15]
 [70 83 10 29 28 83 43 11 54 41]
 [24 63 47 45 11 51 42 93 21 51]
 [ 8 18 67 13 72 58 38 67 45 52]
 [21 54 38 29 66 95 59 40 50 76]
 [73 17 59 69 90 85 78 10 57  6]
 [30 15  8 54 89 85 17 29 54 52]
 [33 85 16 75 22 82 25 58 65 95]
 [13 49 30 60 75 39 88 43 79 33]
 [20 51 28 81 99 68 28 39 21 60]
 [32 43 18 83 34 72 93 85 96 62]
 [38 71 46 98  6 30 45 10 99 87]
 [99 12 32 98 18 55 81 54 13 73]
 [67 31 67 86 93 95 23 50 60 13]
 [78  3 35  3 93 54  6  8 58 16]
 [18 50 60 46  3 73 99 18 19 92]
 [51  6 61 95 12 49 19 46 75 56]
 [62 17 70 86 23 85  7 62 77 37]
 [26 45 11  8 54  3 25 99 81  0]
 [91 97 66

In [179]:
## sort subsets by cost
## asign number of album occurences in each subset
## select which subsets have the best occurences per cost value
## sum all costs

def solve_greedy(subsets, costs, album_universe):
  total = 0
  winning_list = list()
  subset_cost = list()
  covered_album = set()
  covered_subsets = set()

  # create tuple array (subset, cost, index)
  for i in range(len(subsets)):
    tup = subsets[i], costs[i], i
    subset_cost.append(tup)
  
  # sort tuples by cost value
  sorted_subsets = sorted(subset_cost, key=lambda x: x[1])

  # initialize dictionary with values 0
  occurences_per_index = dict.fromkeys(range(len(costs)),0)

  # select subsets and fill album
  for subset in sorted_subsets:
    index = subset[2]
    if len(covered_album) == len(costs):
      break
    for j in subset[0]:
      if j in album_universe and album_universe.get(j) != 1:
        occurences_per_index[index] += 1
        album_universe[j] = 1
        covered_album.add(j)
        covered_subsets.add(index)


  #compute cost 
  for i in covered_subsets:
    total += costs[i]
    winning_list.append(subsets[i])
    print(subsets[i], i)

  print(sorted(occurences_per_index.items(),  key=lambda x: x[1], reverse=True))

  return winning_list, total, album_universe


In [180]:
lst, tot , univ = solve_greedy(subs, cost_values, album)

print(lst)
print(tot)
print(univ)

[ 3 36 50 25  6 92 99 35 45 46] 2
[25 40 53 39  4 61 61 28 15 30] 3
[ 7 77 74 89 26 91 52 44 11 29] 35
[27 58 97 43 25 94 18 28 70 66] 5
[27  2 83 90 72 51 88 20 96 30] 7
[66 68 42 13 98 41 39 92 74 85] 8
[48 87 23 40 57 57 21 45 53  6] 9
[58 32 48 23  4 82 56 10 10 42] 42
[59 14 95 28 76  9 62 69 57 13] 47
[30 15  8 54 89 85 17 29 54 52] 17
[13 49 30 60 75 39 88 43 79 33] 19
[99 12 32 98 18 55 81 54 13 73] 23
[67 31 67 86 93 95 23 50 60 13] 24
[78  3 35  3 93 54  6  8 58 16] 25
[26 45 11  8 54  3 25 99 81  0] 29
[91 97 66 24 87 44 37 23 48 14] 30
[(29, 6), (19, 5), (17, 4), (30, 4), (47, 4), (42, 3), (3, 2), (7, 2), (8, 2), (23, 2), (24, 2), (25, 2), (35, 2), (2, 1), (5, 1), (9, 1), (0, 0), (1, 0), (4, 0), (6, 0), (10, 0), (11, 0), (12, 0), (13, 0), (14, 0), (15, 0), (16, 0), (18, 0), (20, 0), (21, 0), (22, 0), (26, 0), (27, 0), (28, 0), (31, 0), (32, 0), (33, 0), (34, 0), (36, 0), (37, 0), (38, 0), (39, 0), (40, 0), (41, 0), (43, 0), (44, 0), (45, 0), (46, 0), (48, 0), (49, 0)]
[arra